language: cpp
compiler: g++
install:
  - ./install-peg.sh
  - curl -L http://cpanmin.us | sudo perl - --self-upgrade
  - sudo cpanm Test::Base
  - sudo cpanm File::Which
  - sudo apt-get update
  - sudo apt-get install -y valgrind
script:
  - ./build.sh
  - prove -Iperllib
  - ./build.sh release
  - prove -Iperllib
